### PR TITLE
Update 2016-06-25-problem_mathematicalproofs3.md

### PR DESCRIPTION
**Pull request by gamerthink**
Language corrections.

### CODE REVIEW

**Comment by juanjomadrigal** [comment]
Hi @gamerthink !!

The changes you're pointing out are very nice and clever! However, could you remake this pull request keeping the word 'hypothesis' instead of 'lemma'? The right word should be 'induction hypothesis' or 'inductive hypothesis' according to https://en.wikipedia.org/wiki/Mathematical_induction 

Thank you very much!!

**Comment by gamerthink** [comment]
Of course, but you misread, the "Inductive Hypothesis" is actually the assumption that the theorem holds for $k$, the correct denomination is "Inductive step".

**Comment by juanjomadrigal** [comment]
Awesome!! Thank you very much!!

**Comment by juanjomadrigal** [comment]
Hi @gamerthink !!

Already uploaded! You may see your changes 

http://mathifold.org/en/problem_mathematicalproofs2.html
http://mathifold.org/en/problem_mathematicalproofs3.html
http://mathifold.org/en/problem_limits4.html

Thank you very much!! We will be very happy to see more pull requests ;-)

**Pull request merged**
